### ISSUE TITLE
D5 missing

### ISSUE THREAD

**Issue by rtholmes** [CS410-2015Fall/Group_25_Locl#22]
Hi guys,

We can't find your D5 on the class portal anywhere (the demo doc + video link); any chance you can upload those for us ASAP?

Thanks,

--Reid

**Comment by ghost** [comment]
Hey Reid,

Sorry about the confusion; we tried uploading last night to Coast and the
system was down. We made a private Piazza post to you with our files, and
they are now up on Coast.

Kieran

**Comment by rtholmes** [comment]
Thanks.
